framework:
  rate_limiter:
    sms_registration:
      policy: 'token_bucket'
      limit: '%env(int:SMS_REGISTRATION_RATE_LIMITER_LIMIT)%'
      interval: '%env(SMS_REGISTRATION_RATE_LIMITER_INTERVAL)%'
      rate: { interval: '%env(SMS_REGISTRATION_RATE_LIMITER_RATE_INTERVAL)%', amount: "%env(int:SMS_REGISTRATION_RATE_LIMITER_RATE_AMOUNT)%" }
