
services:

  php:
    container_name: prikhodkin_anton_php
    build:
      context: ./docker/
    environment:
      XDEBUG_CONFIG: ${XDEBUG_CONFIG}
      XDEBUG_MODE: ${XDEBUG_MODE}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./:/var/www/sms-registration
    ports:
      - "80:80"
      - "443:443"


###> doctrine/doctrine-bundle ###
  database:
    container_name: prikhodkin_anton_database
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

  redis:
    image: 'redis:5-alpine'
    hostname: redis
    container_name: prikhodkin_anton_redis
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'


volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
